### ISSUE TITLE
Is this pinning the pubkey?

### ISSUE THREAD

**Issue by molexx** [riramar/pubkey-pin-android#1]
or is it pinning the CA's certificate?

**Comment by riramar** [comment]
This is pinning the entire CA certificate as you can see here https://github.com/riramar/pubkey-pin-android/blob/master/src/org/owasp/pubkeypin/KeyPinStore.java#L38

**Comment by riramar** [comment]
If you want to pin the pubkey only I suggest you to use the Moxie implementation (https://github.com/moxie0/AndroidPinning)
