### ISSUE TITLE
Only gives Public key but not having the server communication process.

### ISSUE THREAD

**Issue by GyanSAwasthi** [riramar/pubkey-pin-android#2]
This is fine and good sample which give public key at run time and displays on the screen but what to do for further communication with the server. Would you please commit the code for server communication and please let us know what is the use of obtained public key.Waiting for your comment and latest commit.Thanks in advance.

**Comment by riramar** [comment]
Hi @penzebra 

The pinning concept is applied only in the client side so there is no custom code or configuration on the server side.
I'd suggest you get more familiarized with the hole pinning concept by reading this page https://www.owasp.org/index.php/Certificate_and_Public_Key_Pinning before implementing.
Specially for the new Android versions there is a better way than the one presented in my example which I think it's a good idea to you take a look.

Regards,
Ricardo Iramar
